version: "3.9"  # optional since v1.27.0
services:
  server:
    build: .
    platform: linux/x86_64
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://jedie20:87654321@cluster0.soimyia.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=Cluster0
      - REDIS_URI=rediss://default:AVNS_cFubUuu6xpDY5JJ2OaR@redis-11431c2c-jesperbd-32d7.aivencloud.com:12011
      